export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const FETCHING_USER = 'FETCHING_USER';
export const FETCHING_USER_FAILED = 'FETCHING_USER_FAILED';

export const FETCHED_PLANE = 'FETCHED_PLANE';
export const FETCHING_PLANE = 'FETCHING_PLANE';
export const GET_PLANE_DETAIL = 'GET_PLANE_DETAIL';
export const ADD_PLANE = 'ADD_PLANE';
export const UPDATE_PLANE = 'UPDATE_PLANE';
export const DELETE_PLANE = 'DELETE_PLANE';
export const FETCHING_PLANE_FAILED = 'FETCHING_PLANE_FAILED';
export const DELETE_MANY_PLANES = 'DELETE_MANY_PLANES';

export const FETCHING_COMPANY = 'FETCHING_COMPANY';
export const FETCHED_COMPANY = 'FETCHED_COMPANY';
export const GET_COMPANY_DETAIL = 'GET_COMPANY_DETAIL';
export const GET_COMPANY_BY_USER = 'GET_COMPANY_BY_USER';
export const ADD_COMPANY = 'ADD_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const FETCHING_COMPANY_FAILED = 'FETCHING_COMPANY_FAILED';
export const DELETE_MANY_COMPANY = 'DELETE_MANY_COMPANY';

export const FETCHING_FLIGHTS = 'FETCHING_FLIGHTS';
export const FETCHED_FLIGHTS = 'FETCHED_FLIGHTS';
export const GET_FLIGHT_DETAIL = 'GET_FLIGHT_DETAIL';
export const ADD_FLIGHT = 'ADD_FLIGHT';
export const UPDATE_FLIGHT = 'UPDATE_FLIGHT';
export const DELETE_FLIGHT = 'DELETE_FLIGHT';
export const FETCHING_FLIGHT_FAILED = 'FETCHING_FLIGHT_FAILED';
export const DELETE_MANY_FLIGHTS = 'DELETE_MANY_FLIGHTS';
