export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const FETCHED_PLANE = 'FETCHED_PLANE';
export const FETCHING_PLANE = 'FETCHING_PLANE';

export const FETCHING_CUSTOMERS = 'FETCHING_CUSTOMERS';
export const FETCHED_CUSTOMERS = 'FETCHED_CUSTOMERS';
