export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const LOGIN = 'LOGIN';
export const FETCHING_USER = 'FETCHING_USER';
export const FETCHING_USER_FAILED = 'FETCHING_USER_FAILED';

export const FETCHED_PLANE = 'FETCHED_PLANE';
export const FETCHING_PLANE = 'FETCHING_PLANE';
export const ADD_PLANE = 'ADD_PLANE';
export const UPDATE_PLANE = 'UPDATE_PLANE';
export const DELETE_PLANE = 'DELETE_PLANE';
export const FETCHING_PLANE_FAILED = 'FETCHING_PLANE_FAILED';
export const DELETE_MANY_PLANES = 'DELETE_MANY_PLANES';

export const FETCHING_CUSTOMERS = 'FETCHING_CUSTOMERS';
export const FETCHED_CUSTOMERS = 'FETCHED_CUSTOMERS';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const FETCHING_CUSTOMER_FAILED = 'FETCHING_CUSTOMER_FAILED';
export const DELETE_MANY_CUSTOMERS = 'DELETE_MANY_CUSTOMERS';

export const FETCHING_FLIGHTS = 'FETCHING_FLIGHTS';
export const FETCHED_FLIGHTS = 'FETCHED_FLIGHTS';
export const ADD_FLIGHT = 'ADD_FLIGHT';
export const UPDATE_FLIGHT = 'UPDATE_FLIGHT';
export const DELETE_FLIGHT = 'DELETE_FLIGHT';
export const FETCHING_FLIGHT_FAILED = 'FETCHING_FLIGHT_FAILED';
export const DELETE_MANY_FLIGHTS = 'DELETE_MANY_FLIGHTS';
